-- 价格拆分表建档：法国 / 大连分表
-- 实际建表由 apply_db_updates.py 与 API 懒创建共用 CREATE_TABLE_SQL

CREATE TABLE IF NOT EXISTS price_split_france (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '内部流水号',
    material_group VARCHAR(8) NOT NULL COMMENT 'A105 或 SS',
    drawing_no VARCHAR(255) NULL COMMENT '图纸号(可含版本)',
    drawing_code VARCHAR(128) NULL COMMENT '纯图纸号',
    drawing_rev VARCHAR(32) NULL COMMENT '图纸版本',
    material_no VARCHAR(100) NOT NULL COMMENT 'R3P 物料号',
    part_no VARCHAR(100) NULL COMMENT 'AP1 料号',
    ref_part_no VARCHAR(100) NULL COMMENT '对照 AP1',
    ref_material_no VARCHAR(100) NULL COMMENT '对照 R3P',
    description VARCHAR(512) NULL COMMENT '描述',
    flange_type VARCHAR(32) NULL COMMENT '法兰类型',
    dn DECIMAL(10,2) NULL COMMENT 'DN',
    material VARCHAR(32) NULL COMMENT '材质',
    scope VARCHAR(64) NULL COMMENT '范围',
    award_yn VARCHAR(8) NULL COMMENT 'Award Y/N',
    sales_mode VARCHAR(32) NULL COMMENT '寄售/标准',
    year_usage INT NULL COMMENT '年用量',
    has_m16 VARCHAR(8) NULL COMMENT 'M16 Y/N',
    has_through_hole VARCHAR(8) NULL COMMENT '通孔 Y/N',
    has_ptfe_hole VARCHAR(8) NULL COMMENT 'PTFE孔 Y/N',
    steel_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    blanking_weight DECIMAL(18,8) NOT NULL DEFAULT 0,
    ht_blanking_weight DECIMAL(18,8) NOT NULL DEFAULT 0,
    forged_weight DECIMAL(18,8) NOT NULL DEFAULT 0,
    ht_loss DECIMAL(18,8) NOT NULL DEFAULT 0,
    gas_loss DECIMAL(18,8) NOT NULL DEFAULT 0,
    heat_loss DECIMAL(18,8) NOT NULL DEFAULT 0,
    net_weight DECIMAL(18,8) NOT NULL DEFAULT 0,
    recover_weight DECIMAL(18,8) NOT NULL DEFAULT 0,
    scrap_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    blanking_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    forging_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    heat_treatment_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    ht_freight_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    ring_rolling_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    machining_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    ht_machining_extra DECIMAL(18,8) NOT NULL DEFAULT 0,
    drilling_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    grounding_hole_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    hoisting_hole_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    through_hole_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    ptfe_hole_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    m6_hole_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    packing_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    other_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    transport_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    port_surcharge DECIMAL(18,8) NOT NULL DEFAULT 0,
    profit_rate DECIMAL(12,6) NOT NULL DEFAULT 1.070000,
    material_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    total_process_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    net_price DECIMAL(18,8) NOT NULL DEFAULT 0,
    excel_net_price DECIMAL(18,8) NULL,
    price_version VARCHAR(32) NULL,
    source_file VARCHAR(255) NULL,
    source_sheet VARCHAR(128) NULL,
    source_row INT NULL,
    created_by VARCHAR(50) NULL COMMENT '上传者/录入人姓名',
    created_by_user_id INT NULL COMMENT '上传者用户ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    updated_by VARCHAR(50) NULL COMMENT '更改者姓名',
    updated_by_user_id INT NULL COMMENT '更改者用户ID',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更改时间',
    UNIQUE KEY uk_group_material (material_group, material_no),
    INDEX idx_drawing_no (drawing_no),
    INDEX idx_part_no (part_no),
    INDEX idx_material (material)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='法国价格拆分表';

CREATE TABLE IF NOT EXISTS price_split_dalian LIKE price_split_france;
ALTER TABLE price_split_dalian COMMENT='大连价格拆分表';

CREATE TABLE IF NOT EXISTS price_split_operation_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    region VARCHAR(16) NOT NULL COMMENT 'france/dalian',
    row_id BIGINT NULL COMMENT '业务行ID，删除后可空',
    material_group VARCHAR(8) NULL,
    material_no VARCHAR(100) NULL,
    action VARCHAR(32) NOT NULL COMMENT 'create/update/upload/delete',
    operator_user_id INT NULL,
    operator_name VARCHAR(64) NOT NULL DEFAULT '',
    operated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_summary TEXT NULL COMMENT '变更内容 JSON',
    INDEX idx_ps_log_region_row (region, row_id),
    INDEX idx_ps_log_material (region, material_no),
    INDEX idx_ps_log_action (action),
    INDEX idx_ps_log_time (operated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='价格拆分表操作日志';
